### ISSUE TITLE
Markdown highlight disappears after using MatJax

### ISSUE THREAD

**Issue by elbecerrasoto** [hackmdio/hackmd-io-issues#195]
### Is this a hackmd.io issue?

- [x] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

After using a displayed formula with  \$\$  .. \$\$ the syntax highlight stops.
Nonetheless the render of markdown is done correctly.

#### Current behaviour

Nothing is highlighted after using MatJax for formula displaying (\$\$).
I've tried to to changing text editor and theme, still not working.

> Screenshot (optional)

![Screenshot from 2020-07-10 22-10-28](https://user-images.githubusercontent.com/16927293/87216170-3715a780-c2fa-11ea-8f0d-b53ad95378a3.png)

If possible, create a note with reproducible content and share the link with us.

https://hackmd.io/6ohByI6jTze8zPXOdULUbg

#### Expected behaviour

Everything should be hightlighted.

#### Environment

I use HackMD on:

**Desktop**
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.15.0-109-generic
- Browser: Google Chrome
- Browser Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by okdwtr** [comment]
I also found this bug, but it was actually a bit more complicated.
This problem caused by using `$$` alone, too.
You can see syntax highlight if writing `$$` alone after using `$$...$$`.

I've found that new problem occurs when using `$` only 1 alone.
After using `$`, header is normally highlighted (depends on previous state), but bold and italic are not highlighted.
![image](https://user-images.githubusercontent.com/40514744/87840676-e4308700-c8db-11ea-87fb-26979d4f65d1.png)

-> The behavior of `$` and `$$` (two or more in a row) is different

share link of note is [here](https://hackmd.io/nW19rCT3SP26EeOALW5Hhg)

This issue is confirmed on all devices I have.

- Desktop
  - OS: Windows 10 (1909)
  - Browser: Google Chrome
  - Browser Version: 83.0.4103.116 (Official Build) (64-bit)

- Mobile
  - Device: Oneplus 7 pro
  - OS: OxgenOS ob16(based on Android 10)
  - Browser: chrome
  - Browser Version: 84.0.4147.89

I hope this helps in some way...

**Comment by jackycute** [comment]
Hi, `$$` should always be used for the math in block while `$` is used for inline math, for example:

```
$$
abc
$$
```

vs

```
$abc$
```

Otherwise the highlighting in editor will be broken.
