### ISSUE TITLE
CSS on hackmd.io changed

### ISSUE THREAD

**Issue by afrozl** [hackmdio/hackmd-io-issues#286]
### Is this a hackmd.io issue?

- [X ] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem
 CSS appears to have been arbitrarily changed
All headers are now being transformed to uppercase in slide mode

```
text-transform: var(--r-heading-text-transform);

```
--r-heading-text-transform: uppercase;

More worryingly, this is the second release in a row that has introduced new bugs. Obviously, I can correct this by adding custom styles in the template, but these types of changes should be documented so we can address them before new releases.

**Comment by Yukaii** [comment]
Hi @afrozl, we're sorry for the inconvenience, this is due to the update of the Reveal.js upgrade. In the last release, we restore the default behavior of [Reveal.js themes](https://revealjs.com/themes/). Themes like **black** or **serif** will not  be overwritten:

| default theme | black theme | serif theme |
| :---:|:--:|:--:|
| ![Web キャプチャ_20-12-2021_114552_hackmd io](https://user-images.githubusercontent.com/4230968/146708915-7aa69f13-b4d2-4427-bd56-14493edbfebd.jpeg) | ![Web キャプチャ_20-12-2021_11463_hackmd io](https://user-images.githubusercontent.com/4230968/146708940-e2c5c4ff-1e94-43ff-abd3-6b05fc0f2c69.jpeg) | ![Web キャプチャ_20-12-2021_11469_hackmd io](https://user-images.githubusercontent.com/4230968/146708943-a050a199-878b-4078-a7a7-88f9dbd6918f.jpeg)|
| [link](https://hackmd.io/@yukai-hackmd/default-theme#/) | [link](https://hackmd.io/@yukai-hackmd/black-theme#/) | [link](https://hackmd.io/@yukai-hackmd/serif-theme#/)|

You can see that the default theme (without setting the `theme: some-theme` attributes in YAML) is just a slightly modified black theme with title uppercase transformation and other small edits. To restore your old slide, please try removing the `theme: black` if you have it. And thanks for your suggestion to our release, we'll keep making our upgrade progress more accessible and transparent.
