### ISSUE TITLE
Disable Word Wrap

### ISSUE THREAD

**Issue by njlr** [hackmdio/hackmd-io-issues#78]
I am working on a document with long lines (large Markdown table) and I cannot find an option to disable word-wrap. 

Is this an option? 

 * If so, this option should be made easier to find
 * If not, this should be possible

**Comment by NyaMisty** [comment]
Well is there any progress made?

**Comment by jackycute** [comment]
Word wrap option is now available in the editor preferences along with table tool!
https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-table

<img width="370" alt="螢幕快照 2019-12-25 上午12 13 57" src="https://user-images.githubusercontent.com/2639151/71419651-76a4db00-26ab-11ea-9299-d789571258b9.png">

**Comment by ssbarnea** [comment]
Something is clearly not ok about this because the editor wrap seems to not be converted into continous text in HTML view.

We all know that only double newlines in markdown source gets converted into a newline in HTML but somehow I find impossible to achieve that with hackmd.io.

I need to keep lines in source below 80 chars, so we can review them, but when I do this the rendering in HTML view gets broken.
